# Welcome to Jekyll!

# Website settings
title: WagnerDominik
description: Dominik Wagners personal website,use Jekyll and github pages.
keywords: 
baseurl: # if you have suburl as homepage like '/homepage', please change it to '/homepage'
url: http://wagnerdominik.at
img_path: /Jalpc/static/assets/img/blog  # url should be changed to '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: WagnerDominik  # Be used at blog posts' author.
  first_name: Dominik  # Be used at index page about me section.
  last_name: Wagner  # Be used at index page about me section.
  cv:   # A online CV can be printed as PDF, leave blank if you don't have now
  email: dominik.wagner@sz-ybbs.ac.at # Leave blank if you don't have now
  facebook_username:  # Leave blank if you don't have now
  github_username: wgnrd  # Leave blank if you don't have now
  avatar: /static/assets/img/landing/avatar.jpg  # upload your avatar at directory and edit it.
  skill_icon1:
    - name: icon-csharp
    - name: fa-github
  skill_icon2:
    - name: fa-linux
    - name: icon-raspberrypi
  desc: Introduce myself will be here.

# comment
disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
#  name: jalpc
#  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  # id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off  # type 'on'/'off' to choice display donation button at post page or not


# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
